title:            Liucheng Xu
description:      It is our light, not our darkness that frightens us.
url:              # Site url.
github_username: liuchengxu
disqus_shortname: xuliuchengxlc  # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics: UA-73260325-1  #

kramdown:
  input:    GFM
  syntax_highlighter:    rouge

defaults:
    -
        scope:
            path:    "_posts"
            type:    "posts"
        values:
          layout:    "post"
          disqus:    "y"
          author:    "Liucheng Xu"
