title:            Yue Zhang
description:      It is our light, not our darkness that frightens us.
baseurl:          /blog-cn
url:              yuezhang.org
github_card:      # you need to replace the current github-card. ( leave blank if unwanted. )
google_analytics: # (leave blank if unwanted )

kramdown:
  input:    GFM
  syntax_highlighter:    rouge

defaults:
    -
        scope:
            path:    "_posts"
            type:    "posts"
        values:
          layout:    "post"
          disqus:    "y"
          author:    "yue zhang"

theme: jekyll-theme-cayman
